export type RoomId = "sleep" | "clothes" | "knits" | "gifts" | "accessories" | "bath";
export type SizeId = string;
export type OccasionId = "everyday" | "sleep" | "coming-home" | "gift" | "keepsake";
export type Locale = "en" | "es";

export type Product = {
  slug: string;
  name: { en: string; es: string };
  price: number;
  room: RoomId;
  sizes: SizeId[];
  occasions: OccasionId[];
  color: string;
  fabric: { en: string; es: string };
  care: { en: string; es: string };
  blurb: { en: string; es: string };
  story: { en: string; es: string };
  image: string;
  featured?: boolean;
  isNew?: boolean;
  related: string[];
};

export const ROOMS: {
  id: RoomId;
  name: { en: string; es: string };
  line: { en: string; es: string };
  image: string;
}[] = [
  {
    id: "sleep",
    name: { en: "Sleep", es: "Dormir" },
    line: { en: "Sleepers — footies and zip pajamas.", es: "Enterizos y pijamas con zipper." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/9e0fff057d8886469f09a983a4ae3e5439848153/original.jpeg",
  },
  {
    id: "clothes",
    name: { en: "Clothes", es: "Ropa" },
    line: { en: "Rompers, bubbles, sets.", es: "Mamelucos, bubbles y conjuntos." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/95c0d5dadad4022259a96c650a2f3639b107dd90/original.jpeg",
  },
  {
    id: "knits",
    name: { en: "Knits", es: "Tejidos" },
    line: { en: "Sweaters, blankets, keepers.", es: "Suéteres, mantas, lo que se guarda." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/4a6b1cac35c56ac9e2840cea474e08700a033c4a/original.jpeg",
  },
  {
    id: "gifts",
    name: { en: "Gifts", es: "Regalos" },
    line: { en: "Sets and keepsakes.", es: "Sets y recuerdos." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/c462f8be5277636dd82d41142d3856934bb6fd1c/original.jpeg",
  },
  {
    id: "accessories",
    name: { en: "Accessories", es: "Accesorios" },
    line: { en: "Beanies, booties, bows.", es: "Gorros, patucos y moños." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/14786f95ef604cfb7e2e9c05b2ba2c4c23c17686/original.jpeg",
  },
  {
    id: "bath",
    name: { en: "Bath", es: "Baño" },
    line: { en: "Wash, balm, and skin.", es: "Lavado, bálsamo y piel." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/13590255886dab89e74dfe1952070b4759d2a8ba/original.jpeg",
  },
];


export const COMING_HOME_OUTFITS: {
  id: string;
  name: { en: string; es: string };
  slugs: string[];
}[] = [
  {
    id: "little-sister-peony",
    name: { en: "Little Sister, Peony", es: "Hermanita, Peony" },
    slugs: [
      "sibling-announcement-romper-little-sister-peony-rf7eak",
      "knit-bow-headband-peony-d4b3d3",
    ],
  },
  {
    id: "little-brother-sky",
    name: { en: "Little Brother, Sky", es: "Hermanito, Sky" },
    slugs: [
      "sibling-announcement-romper-little-brother-sky-igkrsz",
      "knit-pom-beanie-sky-wiv4xp",
      "knit-tie-booties-sky-pyftzb",
    ],
  },
  {
    id: "rosewater-first-day",
    name: { en: "Rosewater first day", es: "Rosewater, el primer día" },
    slugs: [
      "flutter-sleeve-romper-rosewater-wph6gh",
      "pointelle-topknot-bow-rosewater-sdnvc6",
    ],
  },
];

export const PRIMARY_ROOMS = ROOMS.filter((r) =>
  r.id === "sleep" || r.id === "clothes" || r.id === "knits" || r.id === "gifts",
);

export const PRIMARY_SIZES: SizeId[] = ["NB", "0-3M", "3-6M", "6-12M"];

export const SIZES: SizeId[] = [
  "NB",
  "0-3M",
  "0-6M",
  "3-6M",
  "6M",
  "6-9M",
  "6-12M",
  "6-18M",
  "12M",
  "12-18M",
  "18-24M",
  "One size",
];

export const SIZE_LABEL: Record<string, { en: string; es: string; hint: { en: string; es: string } }> = {
  "NB": {
    en: "Newborn",
    es: "Recién nacido",
    hint: { en: "Up to ~8 lb / first weeks", es: "Hasta ~3.6 kg / primeras semanas" },
  },
  "0-3M": {
    en: "0–3 months",
    es: "0–3 meses",
    hint: { en: "About 8–12 lb", es: "Aprox. 3.6–5.4 kg" },
  },
  "0-6M": {
    en: "0–6 months",
    es: "0–6 meses",
    hint: { en: "About 8–16 lb", es: "Aprox. 3.6–7.3 kg" },
  },
  "3-6M": {
    en: "3–6 months",
    es: "3–6 meses",
    hint: { en: "About 12–16 lb", es: "Aprox. 5.4–7.3 kg" },
  },
  "6M": {
    en: "6 months",
    es: "6 meses",
    hint: { en: "About 16–18 lb", es: "Aprox. 7.3–8.2 kg" },
  },
  "6-9M": {
    en: "6–9 months",
    es: "6–9 meses",
    hint: { en: "About 16–20 lb", es: "Aprox. 7.3–9 kg" },
  },
  "6-12M": {
    en: "6–12 months",
    es: "6–12 meses",
    hint: { en: "About 16–22 lb", es: "Aprox. 7.3–10 kg" },
  },
  "6-18M": {
    en: "6–18 months",
    es: "6–18 meses",
    hint: { en: "About 16–24 lb", es: "Aprox. 7.3–11 kg" },
  },
  "12M": {
    en: "12 months",
    es: "12 meses",
    hint: { en: "About 20–22 lb", es: "Aprox. 9–10 kg" },
  },
  "12-18M": {
    en: "12–18 months",
    es: "12–18 meses",
    hint: { en: "About 22–26 lb", es: "Aprox. 10–12 kg" },
  },
  "18-24M": {
    en: "18–24 months",
    es: "18–24 meses",
    hint: { en: "About 26–30 lb", es: "Aprox. 12–14 kg" },
  },
  "One size": {
    en: "One size",
    es: "Talla única",
    hint: { en: "Blankets, gifts, most knits", es: "Mantas, regalos, la mayoría de tejidos" },
  },
};

export const OCCASIONS: { id: OccasionId; name: { en: string; es: string } }[] = [
  { id: "coming-home", name: { en: "Coming home", es: "Bienvenida" } },
  { id: "everyday", name: { en: "Everyday", es: "Todos los días" } },
  { id: "sleep", name: { en: "Sleep", es: "Dormir" } },
  { id: "gift", name: { en: "Shower gift", es: "Regalo de baby shower" } },
  { id: "keepsake", name: { en: "Keepsake", es: "Para guardar" } },
];

export const WRAP_PRICE = 1200;
export const SHIP_FLAT = 800;
export const SHIP_FREE_AT = 7500;

export const PRODUCTS: Product[] = [
  {
    slug: "a-day-at-the-beach-gift-set-sbniau",
    name: { en: "A Day at the Beach Gift Set", es: "A Day at the Beach Gift Set" },
    price: 3299,
    room: "gifts",
    sizes: ["One size"],
    occasions: ["gift", "everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "Clothes meant to give — a beach-day set, ready as a gift. Not wrap; the pieces themselves.", es: "Ropa para regalar — un set de día de playa, listo como regalo. No es el empaque; son las piezas." },
    story: { en: "Clothes meant to give — a beach-day set, ready as a gift. Not wrap; the pieces themselves.", es: "Ropa para regalar — un set de día de playa, listo como regalo. No es el empaque; son las piezas." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/c462f8be5277636dd82d41142d3856934bb6fd1c/original.jpeg",
    related: ["heirloom-knit-baby-blanket-biscotti-2fwml3", "baby-booties-biscotti-bj5w54", "baby-sweater-and-shorts-set-biscotti-yy3asl"],
  },
  {
    slug: "baby-blue-bow-printed-bubble-57o64t",
    name: { en: "Baby Blue Bow Printed Bubble", es: "Baby Blue Bow Printed Bubble" },
    price: 2599,
    room: "clothes",
    sizes: ["3-6M"],
    occasions: ["everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "Bubble in baby blue with a bow print. One piece, snap legs, light enough for warm days.", es: "Bubble en azul bebé con moños. Una sola pieza, broches en las piernas, ligero para días cálidos." },
    story: { en: "Bubble in baby blue with a bow print. One piece, snap legs, light enough for warm days.", es: "Bubble en azul bebé con moños. Una sola pieza, broches en las piernas, ligero para días cálidos." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/a6b8e81c973250689204ebda771f495b4ae6678d/original.jpeg",
    related: ["a-day-at-the-beach-gift-set-sbniau", "baby-girl-romper-autumn-r7y5mx", "bamboo-head-wrap-midnight-skelly-lsvc2u"],
  },
  {
    slug: "baby-booties-biscotti-bj5w54",
    name: { en: "Baby Booties – Biscotti", es: "Baby Booties – Biscotti" },
    price: 2000,
    room: "accessories",
    sizes: ["One size"],
    occasions: ["everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "Knit booties in biscotti. Small finish for a set already on the table.", es: "Botitas de punto en biscotti. El remate chico de un conjunto ya puesto." },
    story: { en: "Knit booties in biscotti. Small finish for a set already on the table.", es: "Botitas de punto en biscotti. El remate chico de un conjunto ya puesto." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/14786f95ef604cfb7e2e9c05b2ba2c4c23c17686/original.jpeg",
    related: ["baby-toboggan-biscotti-eogpky", "knit-bow-headband-peony-d4b3d3", "knit-pom-beanie-sky-wiv4xp"],
  },
  {
    slug: "baby-character-bubble-cmfxxc",
    name: { en: "Baby Character Bubble", es: "Baby Character Bubble" },
    price: 2599,
    room: "clothes",
    sizes: ["3-6M"],
    occasions: ["everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "/images/teddy.png",
    related: ["a-day-at-the-beach-gift-set-sbniau", "baby-blue-bow-printed-bubble-57o64t", "baby-girl-romper-autumn-r7y5mx"],
  },
  {
    slug: "baby-girl-romper-autumn-r7y5mx",
    name: { en: "Baby Girl Romper Autumn", es: "Baby Girl Romper Autumn" },
    price: 2899,
    room: "clothes",
    sizes: ["6-12M", "0-6M"],
    occasions: ["everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "Romper cut for everyday wear. Autumn in the name; the cloth stays usable past the season.", es: "Romper para el día a día. Autumn en el nombre; la tela sirve más allá de la temporada." },
    story: { en: "Romper cut for everyday wear. Autumn in the name; the cloth stays usable past the season.", es: "Romper para el día a día. Autumn en el nombre; la tela sirve más allá de la temporada." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/8ebd8af1f31383357468d08522498335c1641244/original.jpeg",
    related: ["a-day-at-the-beach-gift-set-sbniau", "baby-blue-bow-printed-bubble-57o64t", "bamboo-head-wrap-midnight-skelly-lsvc2u"],
  },
  {
    slug: "baby-sweater-and-shorts-set-biscotti-yy3asl",
    name: { en: "Baby Sweater & Shorts Set – Biscotti", es: "Baby Sweater & Shorts Set – Biscotti" },
    price: 4800,
    room: "gifts",
    sizes: ["NB"],
    occasions: ["coming-home", "everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "Knit sweater and shorts in biscotti. A set that reads finished without trying.", es: "Suéter de punto y shorts en biscotti. Un conjunto que se ve completo sin esfuerzo." },
    story: { en: "Knit sweater and shorts in biscotti. A set that reads finished without trying.", es: "Suéter de punto y shorts en biscotti. Un conjunto que se ve completo sin esfuerzo." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/1ea543737e2bdb158f8d9cde1a53c09c802f4ad6/original.jpeg",
    featured: true,
    related: ["cozy-sweater-halloween-zybclj", "merry-sweater-pink-7juidj", "merry-sweater-red-z37voj"],
  },
  {
    slug: "baby-toboggan-biscotti-eogpky",
    name: { en: "Baby Toboggan – Biscotti", es: "Baby Toboggan – Biscotti" },
    price: 2000,
    room: "accessories",
    sizes: ["0-3M"],
    occasions: ["everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "Toboggan in biscotti knit. Soft crown, same palette as the booties and blanket.", es: "Gorro toboggan en punto biscotti. Corona suave, misma paleta que botitas y manta." },
    story: { en: "Toboggan in biscotti knit. Soft crown, same palette as the booties and blanket.", es: "Gorro toboggan en punto biscotti. Corona suave, misma paleta que botitas y manta." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/4644a98fc2dc6238423b922d82053da3a1a474af/original.jpeg",
    related: ["baby-booties-biscotti-bj5w54", "knit-bow-headband-peony-d4b3d3", "knit-pom-beanie-sky-wiv4xp"],
  },
  {
    slug: "bamboo-head-wrap-midnight-skelly-lsvc2u",
    name: { en: "Bamboo Head Wrap – Midnight Skelly", es: "Bamboo Head Wrap – Midnight Skelly" },
    price: 1500,
    room: "accessories",
    sizes: ["One size"],
    occasions: ["everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/2dc14e650814ad27021ba824b07b3f3cdb331b9a/original.jpeg",
    related: ["a-day-at-the-beach-gift-set-sbniau", "baby-blue-bow-printed-bubble-57o64t", "baby-girl-romper-autumn-r7y5mx"],
  },
  {
    slug: "bamboo-zip-pajamas-santa-teddy-mnzwbt",
    name: { en: "Bamboo Zip Pajamas – Santa Teddy", es: "Bamboo Zip Pajamas – Santa Teddy" },
    price: 3900,
    room: "sleep",
    sizes: ["0-3M", "3-6M", "6-12M", "12-18M"],
    occasions: ["sleep", "everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "/images/teddy.png",
    related: ["blue-lattice-bamboo-wrap-footie-zi3kuf", "bluebell-heirloom-vine-bamboo-wrap-footie-kgz44i", "soft-blue-vine-bamboo-wrap-footie-7hc7jb"],
  },
  {
    slug: "barrier-boost-skin-barrier-soothing-stick-3aii3g",
    name: { en: "Barrier Boost Skin Barrier Soothing Stick", es: "Barrier Boost Skin Barrier Soothing Stick" },
    price: 1499,
    room: "bath",
    sizes: ["One size"],
    occasions: ["gift"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/13590255886dab89e74dfe1952070b4759d2a8ba/original.jpeg",
    related: ["bundle-of-joy-mini-kit-ewg-and-fragrance-free-lqwcyx", "cherry-on-top-hair-conditioner-bu2hvp", "cherry-on-top-hair-detangling-and-conditioning-s-tvck27"],
  },
  {
    slug: "black-checkered-baby-boy-romper-with-pocket-bpceae",
    name: { en: "Black Checkered Baby Boy Romper With Pocket", es: "Black Checkered Baby Boy Romper With Pocket" },
    price: 2499,
    room: "clothes",
    sizes: ["6-12M"],
    occasions: ["everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "Black checkered romper with a pocket. Everyday cut, quiet grid.", es: "Romper de cuadros negros con bolsillo. Corte de diario, cuadrícula quieta." },
    story: { en: "Black checkered romper with a pocket. Everyday cut, quiet grid.", es: "Romper de cuadros negros con bolsillo. Corte de diario, cuadrícula quieta." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/a03f78d2e821384e9a75e548a32f7f5384cb16ed/original.jpeg",
    featured: true,
    related: ["a-day-at-the-beach-gift-set-sbniau", "baby-blue-bow-printed-bubble-57o64t", "baby-girl-romper-autumn-r7y5mx"],
  },
  {
    slug: "blue-lattice-bamboo-wrap-footie-zi3kuf",
    name: { en: "Blue Lattice Bamboo Wrap Footie", es: "Blue Lattice Bamboo Wrap Footie" },
    price: 2899,
    room: "sleep",
    sizes: ["0-3M", "3-6M", "6-9M"],
    occasions: ["sleep", "everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "Wrap footie in blue lattice bamboo. Soft close at the chest, easy legs for changing.", es: "Footie envolvente de bamboo en lattice azul. Cierre suave al pecho, piernas fáciles para cambiar." },
    story: { en: "Wrap footie in blue lattice bamboo. Soft close at the chest, easy legs for changing.", es: "Footie envolvente de bamboo en lattice azul. Cierre suave al pecho, piernas fáciles para cambiar." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/9e0fff057d8886469f09a983a4ae3e5439848153/original.jpeg",
    featured: true,
    related: ["bluebell-heirloom-vine-bamboo-wrap-footie-kgz44i", "soft-blue-vine-bamboo-wrap-footie-7hc7jb", "a-day-at-the-beach-gift-set-sbniau"],
  },
  {
    slug: "bluebell-heirloom-vine-bamboo-wrap-footie-kgz44i",
    name: { en: "Bluebell Heirloom Vine Bamboo Wrap Footie", es: "Bluebell Heirloom Vine Bamboo Wrap Footie" },
    price: 2899,
    room: "sleep",
    sizes: ["3-6M", "6-9M"],
    occasions: ["sleep", "keepsake", "everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/58fd45daf2883e534a47ba1b9f0d7cdfaecc72c6/original.jpeg",
    related: ["blue-lattice-bamboo-wrap-footie-zi3kuf", "soft-blue-vine-bamboo-wrap-footie-7hc7jb", "a-day-at-the-beach-gift-set-sbniau"],
  },
  {
    slug: "boy-s-birthday-classic-bubble-vpx44l",
    name: { en: "Boy's Birthday Classic Bubble", es: "Boy's Birthday Classic Bubble" },
    price: 3600,
    room: "clothes",
    sizes: ["6M", "12M"],
    occasions: ["everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/0b4917ec6257dd86270251b66db33e1eb44cac8c/original.jpeg",
    related: ["a-day-at-the-beach-gift-set-sbniau", "baby-blue-bow-printed-bubble-57o64t", "baby-girl-romper-autumn-r7y5mx"],
  },
  {
    slug: "bundle-of-joy-mini-kit-ewg-and-fragrance-free-lqwcyx",
    name: { en: "Bundle of Joy Mini Kit – EWG & Fragrance Free", es: "Bundle of Joy Mini Kit – EWG & Fragrance Free" },
    price: 1499,
    room: "gifts",
    sizes: ["One size"],
    occasions: ["gift"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/ca00f92da5ac95eaf369d4cf44ae3148ab90fba0/original.jpeg",
    related: ["barrier-boost-skin-barrier-soothing-stick-3aii3g", "cherry-on-top-hair-conditioner-bu2hvp", "cherry-on-top-hair-detangling-and-conditioning-s-tvck27"],
  },
  {
    slug: "cardigan-jacket-two-piece-set-z5cyun",
    name: { en: "Cardigan Jacket Two-Piece Set", es: "Cardigan Jacket Two-Piece Set" },
    price: 4099,
    room: "gifts",
    sizes: ["6-12M", "0-6M"],
    occasions: ["everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "/images/teddy.png",
    related: ["baby-sweater-and-shorts-set-biscotti-yy3asl", "cozy-sweater-halloween-zybclj", "merry-sweater-pink-7juidj"],
  },
  {
    slug: "checkered-smile-baby-boy-bubble-4ymgr7",
    name: { en: "Checkered Smile Baby Boy Bubble", es: "Checkered Smile Baby Boy Bubble" },
    price: 2299,
    room: "clothes",
    sizes: ["6-12M"],
    occasions: ["everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/6b717eec55fe9d4c8c6b882cf7d37c9a97dc7804/original.jpeg",
    related: ["a-day-at-the-beach-gift-set-sbniau", "baby-blue-bow-printed-bubble-57o64t", "baby-girl-romper-autumn-r7y5mx"],
  },
  {
    slug: "cherry-on-top-hair-conditioner-bu2hvp",
    name: { en: "Cherry on Top Hair Conditioner", es: "Cherry on Top Hair Conditioner" },
    price: 1299,
    room: "bath",
    sizes: ["One size"],
    occasions: ["gift"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/8f5dcfdaf22d9e7cd3ce88f6e12299052c833929/original.jpeg",
    related: ["barrier-boost-skin-barrier-soothing-stick-3aii3g", "bundle-of-joy-mini-kit-ewg-and-fragrance-free-lqwcyx", "cherry-on-top-hair-detangling-and-conditioning-s-tvck27"],
  },
  {
    slug: "cherry-on-top-hair-detangling-and-conditioning-s-tvck27",
    name: { en: "Cherry on Top Hair Detangling & Conditioning Spray", es: "Cherry on Top Hair Detangling & Conditioning Spray" },
    price: 1099,
    room: "bath",
    sizes: ["One size"],
    occasions: ["gift"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/7bde63045c1330e3dad9bea3df470c092d1ba8fd/original.jpeg",
    related: ["barrier-boost-skin-barrier-soothing-stick-3aii3g", "bundle-of-joy-mini-kit-ewg-and-fragrance-free-lqwcyx", "cherry-on-top-hair-conditioner-bu2hvp"],
  },
  {
    slug: "cotton-sweater-cardigan-shorts-sbuww5",
    name: { en: "Cotton Sweater Cardigan Shorts", es: "Cotton Sweater Cardigan Shorts" },
    price: 2699,
    room: "knits",
    sizes: ["6-12M", "0-6M"],
    occasions: ["everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "/images/teddy.png",
    related: ["baby-sweater-and-shorts-set-biscotti-yy3asl", "cozy-sweater-halloween-zybclj", "merry-sweater-pink-7juidj"],
  },
  {
    slug: "cowgirl-cutie-boots-plaid-romper-hiqk6x",
    name: { en: "Cowgirl Cutie Boots Plaid Romper", es: "Cowgirl Cutie Boots Plaid Romper" },
    price: 2099,
    room: "clothes",
    sizes: ["0-3M", "3-6M", "6-12M", "12-18M", "18-24M"],
    occasions: ["everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/e825753d5228e8a335da810eb85efcd6bcd5b4ac/original.jpeg",
    related: ["a-day-at-the-beach-gift-set-sbniau", "baby-blue-bow-printed-bubble-57o64t", "baby-girl-romper-autumn-r7y5mx"],
  },
  {
    slug: "cozy-sweater-halloween-zybclj",
    name: { en: "Cozy Sweater – Halloween", es: "Cozy Sweater – Halloween" },
    price: 3800,
    room: "knits",
    sizes: ["3-6M", "6-12M", "12-18M", "18-24M"],
    occasions: ["everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/07f6910d52e668bcb321538e54e6b73fec511a12/original.jpeg",
    related: ["baby-sweater-and-shorts-set-biscotti-yy3asl", "merry-sweater-pink-7juidj", "merry-sweater-red-z37voj"],
  },
  {
    slug: "cuddle-cloud-all-over-lotion-5lm4rm",
    name: { en: "Cuddle Cloud All Over Lotion", es: "Cuddle Cloud All Over Lotion" },
    price: 1599,
    room: "bath",
    sizes: ["One size"],
    occasions: ["gift"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "/images/teddy.png",
    related: ["barrier-boost-skin-barrier-soothing-stick-3aii3g", "bundle-of-joy-mini-kit-ewg-and-fragrance-free-lqwcyx", "cherry-on-top-hair-conditioner-bu2hvp"],
  },
  {
    slug: "flutter-sleeve-romper-rosewater-wph6gh",
    name: { en: "Flutter Sleeve Romper – Rosewater", es: "Flutter Sleeve Romper – Rosewater" },
    price: 3600,
    room: "clothes",
    sizes: ["NB"],
    occasions: ["coming-home", "everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "Flutter-sleeve romper in rosewater. Light at the shoulder, ready for the first day home.", es: "Romper de manga flutter en rosewater. Ligero en el hombro, listo para el primer día en casa." },
    story: { en: "Flutter-sleeve romper in rosewater. Light at the shoulder, ready for the first day home.", es: "Romper de manga flutter en rosewater. Ligero en el hombro, listo para el primer día en casa." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/2a88c042b13adc44134141e47a09a7624d11037a/original.jpeg",
    featured: true,
    related: ["a-day-at-the-beach-gift-set-sbniau", "baby-blue-bow-printed-bubble-57o64t", "baby-girl-romper-autumn-r7y5mx"],
  },
  {
    slug: "full-length-romper-candy-cane-ppvozk",
    name: { en: "Full Length Romper – Candy Cane", es: "Full Length Romper – Candy Cane" },
    price: 3899,
    room: "clothes",
    sizes: ["NB", "0-3M", "3-6M", "6-12M", "12-18M"],
    occasions: ["coming-home", "everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/857f3f3de073fa5fc8b4430e150144ce5a263aaa/original.jpeg",
    related: ["a-day-at-the-beach-gift-set-sbniau", "baby-blue-bow-printed-bubble-57o64t", "baby-girl-romper-autumn-r7y5mx"],
  },
  {
    slug: "full-length-romper-red-bows-bqiove",
    name: { en: "Full Length Romper – Red Bows", es: "Full Length Romper – Red Bows" },
    price: 3800,
    room: "clothes",
    sizes: ["0-3M", "3-6M", "6-12M"],
    occasions: ["everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "Full-length romper with a small red-bow print. One piece that photographs clean.", es: "Romper largo con un estampado chico de moños rojos. Una pieza que se ve limpia en foto." },
    story: { en: "Full-length romper with a small red-bow print. One piece that photographs clean.", es: "Romper largo con un estampado chico de moños rojos. Una pieza que se ve limpia en foto." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/95c0d5dadad4022259a96c650a2f3639b107dd90/original.jpeg",
    featured: true,
    related: ["a-day-at-the-beach-gift-set-sbniau", "baby-blue-bow-printed-bubble-57o64t", "baby-girl-romper-autumn-r7y5mx"],
  },
  {
    slug: "girl-s-birthday-bow-back-set-d2oy54",
    name: { en: "Girl's Birthday Bow Back Set", es: "Girl's Birthday Bow Back Set" },
    price: 3800,
    room: "gifts",
    sizes: ["6M"],
    occasions: ["everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/63d3fac53544a7566fc2a98bda78a550b65b9dfe/original.jpeg",
    related: ["a-day-at-the-beach-gift-set-sbniau", "baby-blue-bow-printed-bubble-57o64t", "baby-girl-romper-autumn-r7y5mx"],
  },
  {
    slug: "heirloom-knit-baby-blanket-biscotti-2fwml3",
    name: { en: "Heirloom Knit Baby Blanket – Biscotti", es: "Heirloom Knit Baby Blanket – Biscotti" },
    price: 4200,
    room: "knits",
    sizes: ["One size"],
    occasions: ["gift", "keepsake", "everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "Heirloom knit in biscotti. Fold it for the crib, or keep it for the drawer that lasts.", es: "Manta de punto heredable en biscotti. Para la cuna, o para el cajón que se queda." },
    story: { en: "Heirloom knit in biscotti. Fold it for the crib, or keep it for the drawer that lasts.", es: "Manta de punto heredable en biscotti. Para la cuna, o para el cajón que se queda." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/4a6b1cac35c56ac9e2840cea474e08700a033c4a/original.jpeg",
    featured: true,
    related: ["a-day-at-the-beach-gift-set-sbniau", "baby-blue-bow-printed-bubble-57o64t", "baby-booties-biscotti-bj5w54"],
  },
  {
    slug: "hug-and-heal-bum-balm-sriwqc",
    name: { en: "Hug & Heal Bum Balm", es: "Hug & Heal Bum Balm" },
    price: 1599,
    room: "bath",
    sizes: ["One size"],
    occasions: ["gift"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/7f414e47171ce1fab58ec79eb90017c090d55e01/original.jpeg",
    related: ["barrier-boost-skin-barrier-soothing-stick-3aii3g", "bundle-of-joy-mini-kit-ewg-and-fragrance-free-lqwcyx", "cherry-on-top-hair-conditioner-bu2hvp"],
  },
  {
    slug: "knit-bow-headband-peony-d4b3d3",
    name: { en: "Knit Bow Headband – Peony", es: "Knit Bow Headband – Peony" },
    price: 1600,
    room: "accessories",
    sizes: ["One size"],
    occasions: ["coming-home", "everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "Knit bow in peony. The small finish beside the Little Sister romper.", es: "Moño de punto en peony. El remate chico junto al romper de Hermanita." },
    story: { en: "Knit bow in peony. The small finish beside the Little Sister romper.", es: "Moño de punto en peony. El remate chico junto al romper de Hermanita." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/4e52fc8902a4fba07d4b80ff03247a4472399072/original.jpeg",
    related: ["baby-booties-biscotti-bj5w54", "baby-toboggan-biscotti-eogpky", "knit-pom-beanie-sky-wiv4xp"],
  },
  {
    slug: "knit-pom-beanie-sky-wiv4xp",
    name: { en: "Knit Pom Beanie – Sky", es: "Knit Pom Beanie – Sky" },
    price: 2400,
    room: "accessories",
    sizes: ["NB"],
    occasions: ["coming-home", "everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "Pom beanie in sky. Soft crown, same palette as the Little Brother romper.", es: "Gorro con pompón en sky. Corona suave, misma paleta que el romper de Hermanito." },
    story: { en: "Pom beanie in sky. Soft crown, same palette as the Little Brother romper.", es: "Gorro con pompón en sky. Corona suave, misma paleta que el romper de Hermanito." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/3380c9a161637e6ad6c912494b3931a6765b4e17/original.jpeg",
    related: ["baby-booties-biscotti-bj5w54", "baby-toboggan-biscotti-eogpky", "knit-bow-headband-peony-d4b3d3"],
  },
  {
    slug: "knit-pom-top-beanie-grey-ddpaf5",
    name: { en: "Knit Pom Top Beanie – Grey", es: "Knit Pom Top Beanie – Grey" },
    price: 2400,
    room: "accessories",
    sizes: ["0-6M", "6-18M"],
    occasions: ["everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/01cb202c413dc6daaa629aabad673be8ff04e68b/original.jpeg",
    related: ["baby-booties-biscotti-bj5w54", "baby-toboggan-biscotti-eogpky", "knit-bow-headband-peony-d4b3d3"],
  },
  {
    slug: "knit-romper-picnic-pinstripe-itwmz6",
    name: { en: "Knit Romper – Picnic Pinstripe", es: "Knit Romper – Picnic Pinstripe" },
    price: 3900,
    room: "clothes",
    sizes: ["0-3M", "3-6M", "6-12M", "12-18M"],
    occasions: ["everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "/images/teddy.png",
    related: ["baby-sweater-and-shorts-set-biscotti-yy3asl", "cozy-sweater-halloween-zybclj", "merry-sweater-pink-7juidj"],
  },
  {
    slug: "knit-tie-booties-sky-pyftzb",
    name: { en: "Knit Tie Booties – Sky", es: "Knit Tie Booties – Sky" },
    price: 2400,
    room: "accessories",
    sizes: ["0-3M"],
    occasions: ["coming-home", "everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "Tie booties in sky. The last fold in the Coming Home box.", es: "Botitas con lazo en sky. El último pliegue de la caja de Bienvenida." },
    story: { en: "Tie booties in sky. The last fold in the Coming Home box.", es: "Botitas con lazo en sky. El último pliegue de la caja de Bienvenida." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/c43ff2ca85283355664dd39ac0a2a6df4e08740b/original.jpeg",
    related: ["baby-booties-biscotti-bj5w54", "baby-toboggan-biscotti-eogpky", "knit-bow-headband-peony-d4b3d3"],
  },
  {
    slug: "knit-topknot-headband-biscotti-j3xys2",
    name: { en: "Knit Topknot Headband – Biscotti", es: "Knit Topknot Headband – Biscotti" },
    price: 1400,
    room: "accessories",
    sizes: ["One size"],
    occasions: ["everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/243802e86cf8fdb1f87ad9e07d444069c3788d7f/original.jpeg",
    related: ["baby-booties-biscotti-bj5w54", "baby-toboggan-biscotti-eogpky", "knit-bow-headband-peony-d4b3d3"],
  },
  {
    slug: "knit-topknot-headband-candy-canes-sltv47",
    name: { en: "Knit Topknot Headband – Candy Canes", es: "Knit Topknot Headband – Candy Canes" },
    price: 1499,
    room: "accessories",
    sizes: ["One size"],
    occasions: ["everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/73166e3e9ad92e88b8e2d12044cbf8a6a4deca9d/original.jpeg",
    related: ["baby-booties-biscotti-bj5w54", "baby-toboggan-biscotti-eogpky", "knit-bow-headband-peony-d4b3d3"],
  },
  {
    slug: "knit-topknot-headband-red-bows-cjpttc",
    name: { en: "Knit Topknot Headband – Red Bows", es: "Knit Topknot Headband – Red Bows" },
    price: 1499,
    room: "accessories",
    sizes: ["One size"],
    occasions: ["everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/fe5824b8f6282e02362ea17e365e7e59287de1a7/original.jpeg",
    related: ["baby-booties-biscotti-bj5w54", "baby-toboggan-biscotti-eogpky", "knit-bow-headband-peony-d4b3d3"],
  },
  {
    slug: "lullaby-lather-hair-and-body-wash-sswmqr",
    name: { en: "Lullaby Lather Hair & Body Wash", es: "Lullaby Lather Hair & Body Wash" },
    price: 1399,
    room: "bath",
    sizes: ["One size"],
    occasions: ["gift"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/d92321723c0511354ebeddf34c498c2706341844/original.jpeg",
    related: ["barrier-boost-skin-barrier-soothing-stick-3aii3g", "bundle-of-joy-mini-kit-ewg-and-fragrance-free-lqwcyx", "cherry-on-top-hair-conditioner-bu2hvp"],
  },
  {
    slug: "merry-sweater-pink-7juidj",
    name: { en: "Merry Sweater – Pink", es: "Merry Sweater – Pink" },
    price: 3900,
    room: "knits",
    sizes: ["6-12M"],
    occasions: ["everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/ca77457225e72047f71823a635cefb9149873381/original.jpeg",
    related: ["baby-sweater-and-shorts-set-biscotti-yy3asl", "cozy-sweater-halloween-zybclj", "merry-sweater-red-z37voj"],
  },
  {
    slug: "merry-sweater-red-z37voj",
    name: { en: "Merry Sweater – Red", es: "Merry Sweater – Red" },
    price: 3900,
    room: "knits",
    sizes: ["6-12M"],
    occasions: ["everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/4a64b9f0a3be370f079d2fc409727a0b93ceab44/original.jpeg",
    related: ["baby-sweater-and-shorts-set-biscotti-yy3asl", "cozy-sweater-halloween-zybclj", "merry-sweater-pink-7juidj"],
  },
  {
    slug: "new-plaid-flutter-sleeve-rwnail",
    name: { en: "New Plaid Flutter Sleeve", es: "New Plaid Flutter Sleeve" },
    price: 2799,
    room: "clothes",
    sizes: ["3-6M", "6-12M"],
    occasions: ["everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "/images/teddy.png",
    related: ["a-day-at-the-beach-gift-set-sbniau", "baby-blue-bow-printed-bubble-57o64t", "baby-girl-romper-autumn-r7y5mx"],
  },
  {
    slug: "pink-bows-romper-mdwtdq",
    name: { en: "Pink Bows Romper", es: "Pink Bows Romper" },
    price: 3899,
    room: "clothes",
    sizes: ["0-3M", "3-6M", "6-12M", "12-18M"],
    occasions: ["everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "/images/teddy.png",
    related: ["a-day-at-the-beach-gift-set-sbniau", "baby-blue-bow-printed-bubble-57o64t", "baby-girl-romper-autumn-r7y5mx"],
  },
  {
    slug: "pointelle-topknot-bow-rosewater-sdnvc6",
    name: { en: "Pointelle Topknot Bow – Rosewater", es: "Pointelle Topknot Bow – Rosewater" },
    price: 1499,
    room: "accessories",
    sizes: ["One size"],
    occasions: ["coming-home", "everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "Pointelle topknot in rosewater. The bow that finishes the flutter romper.", es: "Moño pointelle en rosewater. El lazo que termina el romper flutter." },
    story: { en: "Pointelle topknot in rosewater. The bow that finishes the flutter romper.", es: "Moño pointelle en rosewater. El lazo que termina el romper flutter." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/c923de694d692e92a2d213530caa4c4892ddbf66/original.jpeg",
    related: ["a-day-at-the-beach-gift-set-sbniau", "baby-blue-bow-printed-bubble-57o64t", "baby-girl-romper-autumn-r7y5mx"],
  },
  {
    slug: "pumpkin-pullover-sweater-kdwna7",
    name: { en: "Pumpkin Pullover Sweater", es: "Pumpkin Pullover Sweater" },
    price: 3900,
    room: "knits",
    sizes: ["6-12M"],
    occasions: ["everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/bc1c1eb78069c5043300b61dddafe063e791e063/original.jpeg",
    related: ["baby-sweater-and-shorts-set-biscotti-yy3asl", "cozy-sweater-halloween-zybclj", "merry-sweater-pink-7juidj"],
  },
  {
    slug: "ruffle-romper-red-bows-t3gbcz",
    name: { en: "Ruffle Romper – Red Bows", es: "Ruffle Romper – Red Bows" },
    price: 3699,
    room: "clothes",
    sizes: ["0-3M", "3-6M", "6-12M", "12-18M"],
    occasions: ["everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/fd6bae1a0ca84af3963a696c76ef364e3149908d/original.jpeg",
    related: ["a-day-at-the-beach-gift-set-sbniau", "baby-blue-bow-printed-bubble-57o64t", "baby-girl-romper-autumn-r7y5mx"],
  },
  {
    slug: "sibling-announcement-romper-little-brother-sky-igkrsz",
    name: { en: "Sibling Announcement Romper – Little Brother | Sky", es: "Sibling Announcement Romper – Little Brother | Sky" },
    price: 5000,
    room: "clothes",
    sizes: ["NB", "0-3M"],
    occasions: ["coming-home", "keepsake", "everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "Little Brother in sky. The announcement romper for the ride home.", es: "Hermanito en sky. El romper de anuncio para el regreso a casa." },
    story: { en: "Little Brother in sky. The announcement romper for the ride home.", es: "Hermanito en sky. El romper de anuncio para el regreso a casa." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/4d54ad64ecf976839a263d23b1ec1d27f2374857/original.jpeg",
    related: ["a-day-at-the-beach-gift-set-sbniau", "baby-blue-bow-printed-bubble-57o64t", "baby-girl-romper-autumn-r7y5mx"],
  },
  {
    slug: "sibling-announcement-romper-little-sister-peony-rf7eak",
    name: { en: "Sibling Announcement Romper – Little Sister | Peony", es: "Sibling Announcement Romper – Little Sister | Peony" },
    price: 5000,
    room: "clothes",
    sizes: ["NB", "0-3M"],
    occasions: ["coming-home", "keepsake", "everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "Little Sister in peony. The announcement romper for the first night home.", es: "Hermanita en peony. El romper de anuncio para la primera noche en casa." },
    story: { en: "Little Sister in peony. The announcement romper for the first night home.", es: "Hermanita en peony. El romper de anuncio para la primera noche en casa." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/9458403545120f5f4b0085db332a91eaf41fcfa6/original.jpeg",
    related: ["a-day-at-the-beach-gift-set-sbniau", "baby-blue-bow-printed-bubble-57o64t", "baby-girl-romper-autumn-r7y5mx"],
  },
  {
    slug: "soft-blue-vine-bamboo-wrap-footie-7hc7jb",
    name: { en: "Soft Blue Vine Bamboo Wrap Footie", es: "Soft Blue Vine Bamboo Wrap Footie" },
    price: 2899,
    room: "sleep",
    sizes: ["0-3M", "3-6M"],
    occasions: ["sleep", "everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "Soft blue vine bamboo for the ride home. Wrap front, quiet print, made for the first fold.", es: "Bamboo soft blue vine para el regreso a casa. Frente envolvente, estampado quieto, para el primer pliegue." },
    story: { en: "Soft blue vine bamboo for the ride home. Wrap front, quiet print, made for the first fold.", es: "Bamboo soft blue vine para el regreso a casa. Frente envolvente, estampado quieto, para el primer pliegue." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/532d58904f76e74e768afd768ffddb1b0b8f3dd7/original.jpeg",
    featured: true,
    related: ["blue-lattice-bamboo-wrap-footie-zi3kuf", "bluebell-heirloom-vine-bamboo-wrap-footie-kgz44i", "a-day-at-the-beach-gift-set-sbniau"],
  },
  {
    slug: "soft-blue-vine-bonnet-lmsqla",
    name: { en: "Soft Blue Vine Bonnet", es: "Soft Blue Vine Bonnet" },
    price: 1299,
    room: "accessories",
    sizes: ["0-3M"],
    occasions: ["everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "Bonnet in the same soft blue vine. The finish for a sleeper already chosen.", es: "Capota en el mismo soft blue vine. El remate de un enterizo ya elegido." },
    story: { en: "Bonnet in the same soft blue vine. The finish for a sleeper already chosen.", es: "Capota en el mismo soft blue vine. El remate de un enterizo ya elegido." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/7ea1859169779baf696acc877e7aa2da3065b345/original.jpeg",
    featured: true,
    related: ["baby-booties-biscotti-bj5w54", "baby-toboggan-biscotti-eogpky", "knit-bow-headband-peony-d4b3d3"],
  },
  {
    slug: "sweatshirt-romper-midnight-skelly-vkksmw",
    name: { en: "Sweatshirt Romper – Midnight Skelly", es: "Sweatshirt Romper – Midnight Skelly" },
    price: 3800,
    room: "clothes",
    sizes: ["3-6M", "6-12M", "12-18M", "18-24M"],
    occasions: ["everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/091d38f190f8212edeff8f6e5cf58500e3edba08/original.jpeg",
    related: ["a-day-at-the-beach-gift-set-sbniau", "baby-blue-bow-printed-bubble-57o64t", "baby-girl-romper-autumn-r7y5mx"],
  },
  {
    slug: "tear-free-shampoo-body-wash-and-bubbles-blueberr-kcjom6",
    name: { en: "Tear-Free Shampoo, Body Wash & Bubbles – Blueberry", es: "Tear-Free Shampoo, Body Wash & Bubbles – Blueberry" },
    price: 1099,
    room: "bath",
    sizes: ["One size"],
    occasions: ["gift"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/fe5715798845be30fa08155ea4b13e5287c2a50b/original.jpeg",
    related: ["barrier-boost-skin-barrier-soothing-stick-3aii3g", "bundle-of-joy-mini-kit-ewg-and-fragrance-free-lqwcyx", "cherry-on-top-hair-conditioner-bu2hvp"],
  },
  {
    slug: "tear-free-shampoo-body-wash-and-bubbles-strawber-2q3tgy",
    name: { en: "Tear-Free Shampoo, Body Wash & Bubbles – Strawberry", es: "Tear-Free Shampoo, Body Wash & Bubbles – Strawberry" },
    price: 1099,
    room: "bath",
    sizes: ["One size"],
    occasions: ["gift"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/e1b74af2f8d6bab7b37459702c24fd4487423d92/original.jpeg",
    related: ["barrier-boost-skin-barrier-soothing-stick-3aii3g", "bundle-of-joy-mini-kit-ewg-and-fragrance-free-lqwcyx", "cherry-on-top-hair-conditioner-bu2hvp"],
  },
  {
    slug: "turkey-flock-gingham-bubble-romper-otl4wy",
    name: { en: "Turkey Flock Gingham Bubble Romper", es: "Turkey Flock Gingham Bubble Romper" },
    price: 2299,
    room: "clothes",
    sizes: ["0-3M", "3-6M", "6-12M", "12-18M", "18-24M"],
    occasions: ["everyday"],
    color: "As shown",
    fabric: { en: "As listed", es: "Como se indica." },
    care: { en: "See garment label.", es: "Ver la etiqueta de la prenda." },
    blurb: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "De la boutique Shia Baby. Empacado en marino, atado con un listón." },
    story: { en: "From the Shia Baby boutique. Packed in navy, tied with a bow.", es: "Elegido una pieza a la vez. El osito va en cada caja." },
    image: "https://items-images-production.s3.us-west-2.amazonaws.com/files/bdf89a2bb5eddca8ed06d59fb6d33597c73df5f6/original.jpeg",
    related: ["a-day-at-the-beach-gift-set-sbniau", "baby-blue-bow-printed-bubble-57o64t", "baby-girl-romper-autumn-r7y5mx"],
  },
];

export const ROOM_COPY: Record<
  RoomId,
  { kicker: { en: string; es: string }; title: { en: string; es: string }; body: { en: string; es: string } }
> = {
  sleep: {
    kicker: { en: "The sleep room", es: "La sala de dormir" },
    title: { en: "Sleepers — footies and zip pajamas.", es: "Enterizos y pijamas con zipper." },
    body: {
      en: "Bamboo that cools, zips that open from the foot, prints small enough to keep. This is the shelf we restock first.",
      es: "Bambú que refresca, zippers que abren desde el pie, estampados lo bastante pequeños para guardar. Este es el estante que reponemos primero.",
    },
  },
  clothes: {
    kicker: { en: "The clothes room", es: "La sala de ropa" },
    title: { en: "Rompers, bubbles, the daytime edit.", es: "Mamelucos, bubbles, la edición del día." },
    body: {
      en: "What goes on after the sleeper. Pieces that look like they were chosen, not ordered by the crate.",
      es: "Lo que se pone después del pijama. Piezas que parecen elegidas, no pedidas por caja.",
    },
  },
  knits: {
    kicker: { en: "The knit room", es: "La sala de tejidos" },
    title: { en: "Sweaters, blankets, the keepers.", es: "Suéteres, mantas, lo que se guarda." },
    body: {
      en: "The things that stay in the house after the size is outgrown.",
      es: "Lo que se queda en la casa cuando la talla se queda chica.",
    },
  },
  gifts: {
    kicker: { en: "The gift room", es: "La sala de regalos" },
    title: { en: "Sets and keepsakes, packed to open.", es: "Sets y recuerdos, listos para abrir." },
    body: {
      en: "Clothes to give. Wrap is a separate service — navy box, teddy tissue, ribbon — if you want the box finished.",
      es: "Ropa para regalar. El envoltorio es aparte — caja marina, papel de seda, listón — si quieres la caja terminada.",
    },
  },
  accessories: {
    kicker: { en: "The accessory shelf", es: "El estante de accesorios" },
    title: { en: "Beanies, booties, a bow.", es: "Gorros, patucos, un moño." },
    body: {
      en: "The small things that finish the box — and stay after the sleeper is outgrown.",
      es: "Lo pequeño que termina la caja — y se queda cuando el enterizo se queda chico.",
    },
  },
  bath: {
    kicker: { en: "Bath & skin", es: "Baño y piel" },
    title: { en: "Further along the shelf.", es: "Más adelante en el estante." },
    body: {
      en: "Wash, balm, and a quiet night. Packed with the clothes if you want the box finished.",
      es: "Lavado, bálsamo, y una noche quieta. Se empaca con la ropa si quieres la caja terminada.",
    },
  },
};

export function getProduct(slug: string) {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function productsInRoom(room: RoomId) {
  return PRODUCTS.filter((p) => p.room === room);
}

export function filterProducts(opts: {
  room?: string;
  size?: string;
  occasion?: string;
  q?: string;
  featured?: boolean;
  isNew?: boolean;
}) {
  return PRODUCTS.filter((p) => {
    if (opts.room && opts.room !== "all" && p.room !== opts.room) return false;
    if (opts.size && opts.size !== "all" && !p.sizes.includes(opts.size)) return false;
    if (opts.occasion && opts.occasion !== "all" && !p.occasions.includes(opts.occasion as OccasionId))
      return false;
    if (opts.featured && !p.featured) return false;
    if (opts.isNew && !p.isNew) return false;
    if (opts.q) {
      const q = opts.q.toLowerCase();
      const hay = `${p.name.en} ${p.name.es} ${p.blurb.en} ${p.blurb.es} ${p.fabric.en} ${p.room}`.toLowerCase();
      if (!hay.includes(q)) return false;
    }
    return true;
  });
}

export function isRoom(id: string): id is RoomId {
  return ROOMS.some((r) => r.id === id);
}

