/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ComingHomeRouteImport } from './routes/coming-home'
import { Route as GiftWrapRouteImport } from './routes/gift-wrap'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as SizeGuideRouteImport } from './routes/size-guide'
import { Route as TheHouseRouteImport } from './routes/the-house'
import { Route as ProductSlugRouteImport } from './routes/product/$slug'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ShopRoomRouteImport } from './routes/shop/$room'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingHomeRoute = ComingHomeRouteImport.update({
  id: '/coming-home',
  path: '/coming-home',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftWrapRoute = GiftWrapRouteImport.update({
  id: '/gift-wrap',
  path: '/gift-wrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const SizeGuideRoute = SizeGuideRouteImport.update({
  id: '/size-guide',
  path: '/size-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const TheHouseRoute = TheHouseRouteImport.update({
  id: '/the-house',
  path: '/the-house',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoomRoute = ShopRoomRouteImport.update({
  id: '/shop/$room',
  path: '/shop/$room',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/coming-home': typeof ComingHomeRoute
  '/gift-wrap': typeof GiftWrapRoute
  '/shipping': typeof ShippingRoute
  '/size-guide': typeof SizeGuideRoute
  '/the-house': typeof TheHouseRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shop/$room': typeof ShopRoomRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/coming-home': typeof ComingHomeRoute
  '/gift-wrap': typeof GiftWrapRoute
  '/shipping': typeof ShippingRoute
  '/size-guide': typeof SizeGuideRoute
  '/the-house': typeof TheHouseRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shop/$room': typeof ShopRoomRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/coming-home': typeof ComingHomeRoute
  '/gift-wrap': typeof GiftWrapRoute
  '/shipping': typeof ShippingRoute
  '/size-guide': typeof SizeGuideRoute
  '/the-house': typeof TheHouseRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shop/$room': typeof ShopRoomRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/coming-home'
    | '/gift-wrap'
    | '/shipping'
    | '/size-guide'
    | '/the-house'
    | '/product/$slug'
    | '/shop/$room'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/coming-home'
    | '/gift-wrap'
    | '/shipping'
    | '/size-guide'
    | '/the-house'
    | '/product/$slug'
    | '/shop/$room'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/coming-home'
    | '/gift-wrap'
    | '/shipping'
    | '/size-guide'
    | '/the-house'
    | '/product/$slug'
    | '/shop/$room'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  ComingHomeRoute: typeof ComingHomeRoute
  GiftWrapRoute: typeof GiftWrapRoute
  ShippingRoute: typeof ShippingRoute
  SizeGuideRoute: typeof SizeGuideRoute
  TheHouseRoute: typeof TheHouseRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ShopRoomRoute: typeof ShopRoomRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-home': {
      id: '/coming-home'
      path: '/coming-home'
      fullPath: '/coming-home'
      preLoaderRoute: typeof ComingHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-wrap': {
      id: '/gift-wrap'
      path: '/gift-wrap'
      fullPath: '/gift-wrap'
      preLoaderRoute: typeof GiftWrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/size-guide': {
      id: '/size-guide'
      path: '/size-guide'
      fullPath: '/size-guide'
      preLoaderRoute: typeof SizeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-house': {
      id: '/the-house'
      path: '/the-house'
      fullPath: '/the-house'
      preLoaderRoute: typeof TheHouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$room': {
      id: '/shop/$room'
      path: '/shop/$room'
      fullPath: '/shop/$room'
      preLoaderRoute: typeof ShopRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  ComingHomeRoute: ComingHomeRoute,
  GiftWrapRoute: GiftWrapRoute,
  ShippingRoute: ShippingRoute,
  SizeGuideRoute: SizeGuideRoute,
  TheHouseRoute: TheHouseRoute,
  ProductSlugRoute: ProductSlugRoute,
  ShopRoomRoute: ShopRoomRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
